#!/opt/hw-py/bin/python
"""Solve the DAB transformer: what leakage inductance does 3 kW need?

The white paper names every semiconductor in the converter and none of the
three parameters that set its power transfer - turns ratio, leakage inductance,
switching frequency. So this does not reproduce the white paper's DAB. It runs
the inverse: for each candidate phase shift, compute the leakage inductance
that delivers the target power, simulate it, and report the current the bridges
would actually carry.

    P = V1 * (V2/n) * phi * (pi - phi) / (2 * pi^2 * f * L)      referred to LV

Phase shift is the design trade. A large phi reaches the power with a large
inductance, which is easy to build into a planar transformer, but circulates
more current and burns it in the bridges. A small phi needs a small, harder to
control inductance. The rms current column is what decides it.

    ./sim/dab/run_dab.py
"""
from __future__ import annotations

import math
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
DECK = os.path.join(HERE, "dab.cir")
OUT = "docs/design/sim-dab.md"

PI = math.pi
VLV, VHV, P_TGT = 48.0, 400.0, 3000.0
NT = VHV / VLV
RLK = 8e-3                      # winding + interconnect, provisional

# BSC190N15NS3, low-voltage bridge. R_ds(on) is the datasheet's 150 V / 19 mohm
# family figure and is NOT yet confirmed against a fetched datasheet - see
# docs/reference/manifest.yaml. Hot R_ds(on) is roughly 1.6x the 25 degC value.
RDSON_LV_HOT = 0.019 * 1.6


def l_for(p: float, phi: float, f: float) -> float:
    return VLV * VLV * phi * (PI - phi) / (2 * PI * PI * f * p)


def run(f: float, phi_deg: float, llk: float):
    with open(DECK) as fh:
        deck = fh.read()
    for key, val in (("FS", f), ("PHIDEG", phi_deg), ("LLK", llk),
                     ("RLK", RLK)):
        deck = re.sub(rf"^\.param {key}=.*$", f".param {key}={val:.10g}",
                      deck, flags=re.M)
    with tempfile.NamedTemporaryFile("w", suffix=".cir", delete=False) as fh:
        fh.write(deck)
        path = fh.name
    try:
        r = subprocess.run(["ngspice", "-b", path], capture_output=True,
                           text=True, timeout=600)
    finally:
        os.unlink(path)
    out = r.stdout + r.stderr
    vals = {m.group(1): float(m.group(2))
            for m in re.finditer(r"^(\w+)\s*=\s*([-\d.e+]+)\s*$", out, re.M)}
    obs = [l.strip() for l in out.splitlines()
           if re.search(r"singular|doesn't converge|Error", l, re.I)]
    return vals, obs


def main() -> int:
    rows, bad = [], 0
    print(f"{'f kHz':>6} {'phi deg':>8} {'L_lk uH':>9} {'L_lk HV uH':>11} "
          f"{'P sim W':>9} {'err':>6} {'I rms A':>8} {'I pk A':>7} "
          f"{'W/FET,bridge x2':>14} {'x4':>14}")
    for f in (100e3, 150e3):
        for phi_deg in (30.0, 45.0, 60.0, 90.0):
            phi = math.radians(phi_deg)
            llk = l_for(P_TGT, phi, f)
            vals, obs = run(f, phi_deg, llk)
            p = abs(vals.get("p_lv", float("nan")))
            err = abs(p - P_TGT) / P_TGT * 100
            irms = vals.get("il_rms", float("nan"))
            if err > 8 or obs:
                bad += 1
            # Conduction loss in the LOW-VOLTAGE bridge. Each switch position
            # conducts for half the cycle, so a device sees I_rms/(sqrt2 * N)
            # with N in parallel; four switch positions each of N devices give
            #   per device  I_rms^2 * Rds / (2 N^2)
            #   whole bridge 2 * I_rms^2 * Rds / N
            # Getting the half-cycle factor wrong understates a device by 2x.
            w2 = irms ** 2 * RDSON_LV_HOT / (2 * 2 ** 2)
            w4 = irms ** 2 * RDSON_LV_HOT / (2 * 4 ** 2)
            b2 = 2 * irms ** 2 * RDSON_LV_HOT / 2
            b4 = 2 * irms ** 2 * RDSON_LV_HOT / 4
            print(f"{f/1e3:6.0f} {phi_deg:8.0f} {llk*1e6:9.3f} "
                  f"{llk*NT*NT*1e6:11.1f} {p:9.0f} {err:5.1f}% {irms:8.1f} "
                  f"{vals.get('il_pk', float('nan')):7.1f} "
                  f"{w2:6.1f}/{b2:6.0f} {w4:6.1f}/{b4:6.0f}")
            for o in obs[:2]:
                print(f"    observation: {o}")
            rows.append(dict(f=f, phi=phi_deg, llk=llk, p=p, err=err,
                             irms=irms, ipk=vals.get("il_pk"), w2=w2, w4=w4,
                             b2=b2, b4=b4, obs=obs))
    write(rows)
    return 1 if bad else 0


def write(rows) -> None:
    o = ["# Dual active bridge — solving for the transformer", "",
         "Generated by `sim/dab/run_dab.py` from `sim/dab/dab.cir` on "
         "ngspice-42. Do not edit by hand.", "",
         "**This is not a simulation of the white paper's DAB.** The white "
         "paper names every semiconductor in the converter (page 8) and none "
         "of the three parameters that set its power transfer — transformer "
         "turns ratio, leakage inductance, switching frequency. What follows "
         "runs the inverse: for each candidate phase shift, the leakage "
         "inductance that delivers 3 kW, simulated, with the current the "
         "bridges would carry.", "",
         f"{VLV:.0f} V to {VHV:.0f} V, turns ratio {NT:.2f}:1, "
         f"{P_TGT/1000:.1f} kW, {RLK*1000:.0f} mΩ loop resistance.", "",
         "| f kHz | φ ° | L_lk µH (LV) | L_lk µH (HV) | P sim W | error | "
         "I rms A | I pk A | W/FET (2 per branch) | LV bridge W | "
         "W/FET (4 per branch) | LV bridge W |",
         "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for r in rows:
        o.append(f"| {r['f']/1e3:.0f} | {r['phi']:.0f} | {r['llk']*1e6:.3f} | "
                 f"{r['llk']*NT*NT*1e6:.1f} | {r['p']:.0f} | {r['err']:.1f}% | "
                 f"{r['irms']:.1f} | {(r['ipk'] or 0):.1f} | {r['w2']:.1f} | "
                 f"{r['b2']:.0f} | {r['w4']:.1f} | {r['b4']:.0f} |")
    obs = [(r["f"], r["phi"], x) for r in rows for x in r["obs"]]
    o += ["", "## Simulator observations", ""]
    o += ([f"* {f/1e3:.0f} kHz φ={p:.0f}°: `{x}`" for f, p, x in obs] if obs
          else ["None. No singular-matrix or convergence warnings on any run."])
    with open(OUT, "w") as fh:
        fh.write("\n".join(o) + "\n")
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    sys.exit(main())
